apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafestatic
  labels:
    app: cafestatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafestatic
  template:
    metadata:
      labels:
        app: cafestatic
    spec:
      containers:
      - name: cafestatic
        image: aadithya001/cafeapp:v1
        ports:
        - containerPort: 80
